// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func home(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `home.templ`, Line: 10, Col: 16}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css\"><script src=\"https://kit.fontawesome.com/c2b6fd3803.js\" crossorigin=\"anonymous\"></script><script type=\"module\" src=\"https://cdn.jsdelivr.net/gh/starfederation/datastar@main/bundles/datastar.js\"></script><style>\n        ul.no-bullets {\n        list-style-type: none;\n        }\n\n        .xspinner {\n        padding: 5.5em;\n        height: 12em;\n        }\n\n        .footer {\n            --bulma-footer-padding: 3rem 1.5rem 3rem;\n        }\n    </style></head><body><section class=\"section\"><div class=\"container\"><h1 class=\"title\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `home.templ`, Line: 35, Col: 29}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</h1><p class=\"subtitle\">Go, Bulma, Datastar</p><div data-on-datastar-fetch=\"$_fetchError = evt.detail.type === 'retrying' || evt.detail.type === 'retry-failed'\"></div><div class=\"box error-message\" data-show=\"$_fetchError\" style=\"position: fixed; bottom: 0em; left: 0em; padding: 1em; z-index: 1000; display: none;\"><p class=\"has-text-danger is-size-4\">Network issues. Please try again later.</p></div><div class=\"columns\"><div class=\"column\"><div class=\"content\">Put some stuff here!<div id=\"top-stories\" data-on-load=\"@get('/top-stories')\"></div><div id=\"say-hi\"><button class=\"button is-primary\" data-on-click=\"@get('/greeting')\">Say Hi</button></div></div></div></div><footer class=\"footer\"><div id=\"site-error\"></div><div class=\"content has-text-centered\"><strong><a href=\"https://sliplane.io\" target=\"_blank\">Sliplane</a></strong> and <strong><a href=\"https://hono.dev\" target=\"_blank\">Hono</a></strong> backend,<br><strong><a href=\"https://data-star.dev/\" target=\"_blank\">DataStar</a></strong> + <strong><a href=\"https://bulma.io/\" target=\"_blank\">Bulma</a></strong> & <strong><a href=\"https://fontawesome.com\">Font Awesome</a></strong> frontend</div></footer></div></section></body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
